#!/bin/bash

set -e

export ZOOCFGDIR=/var/vcap/jobs/zookeeper/config
export ZOO_LOG_DIR=/var/vcap/sys/log/zookeeper
export ZOO_LOG4J_PROP="INFO,CONSOLE,ROLLINGFILE"

export JAVA_HOME=/var/vcap/packages/java/jdk
export PATH=$JAVA_HOME/bin:$PATH

export CLASSPATH=${CLASSPATH:-''}
for jar_dir in $(ls -d /var/vcap/packages/*/*/*.jar); do
  export CLASSPATH=${jar_dir}:$CLASSPATH
done

case $1 in

  start)
    exec /var/vcap/packages/zookeeper/bin/zkServer.sh start-foreground
    ;;

  status)
    exec /var/vcap/packages/zookeeper/bin/zkServer.sh status
    ;;

  cli)
    shift
    exec /var/vcap/packages/zookeeper/bin/zkCli.sh $@
    ;;

  *)
    echo "Usage: $0 {start|status|cli}"
    exit 1
    ;;

esac
exit 0
